sudo: required
language: generic
services:
- docker
env:
  global:
  - BINTRAY_REPO_NAME=debian
  - BINTRAY_USER=yadickson
  - GITHUB_NAME=yadickson
  - GITHUB_EMAIL=yadickson@gmail.com
  - PACKAGE_LICENSE=Apache-2.0
  - PACKAGE_NAME=$(dpkg-parsechangelog | awk '/^Source:/ { print $2 }')
  - PACKAGE_VERSION=$(dpkg-parsechangelog | awk '/^Version:/ { print $2 }' | sed 's/-.*//')
  - PACKAGE_DISTRIBUTION=$(dpkg-parsechangelog | awk '/^Distribution:/ { print $2 }')
  - PACKAGE_RELEASE=$(date '+%Y-%m-%d')
  - TRAVIS_DEBIAN_DERIVATIVE=debian
  - TRAVIS_DEBIAN_DISTRIBUTION=${PACKAGE_DISTRIBUTION}
  - TRAVIS_DEBIAN_GIT_BUILDPACKAGE_OPTIONS="--git-upstream-tree=${PACKAGE_DISTRIBUTION} --git-debian-branch=${PACKAGE_DISTRIBUTION}"
  - TRAVIS_DEBIAN_EXTRA_REPOSITORY="http://dl.bintray.com/yadickson/debian/ ${PACKAGE_DISTRIBUTION} main"
  - TRAVIS_DEBIAN_EXTRA_REPOSITORY_GPG_URL="https://bintray.com/user/downloadSubjectPublicKey?username=bintray"
script:
- wget -O- http://travis.debian.net/script.sh | sed '/deb-src/d' | sh -
before_deploy:
- sed -e "s/__NAME__/${PACKAGE_NAME}/g" .travis.bintray.json.in > .travis.bintray.json
- sed -i "s/__REPO_NAME__/${BINTRAY_REPO_NAME}/g" .travis.bintray.json
- sed -i "s/__SUBJECT__/${BINTRAY_USER}/g" .travis.bintray.json
- sed -i "s/__LICENSE__/${PACKAGE_LICENSE}/g" .travis.bintray.json
- sed -i "s/__VERSION__/${PACKAGE_VERSION}/g" .travis.bintray.json
- sed -i "s/__DISTRIBUTION__/${PACKAGE_DISTRIBUTION}/g" .travis.bintray.json
- sed -i "s/__RELEASE__/${PACKAGE_RELEASE}/g" .travis.bintray.json
- git config --local user.name "${GITHUB_NAME}"
- git config --local user.email "${GITHUB_EMAIL}"
deploy:
  - provider: bintray
    file: ".travis.bintray.json"
    user: "${BINTRAY_USER}"
    key:
      secure: UExxntVVhEuj/XbJzdWycZ6qdSmJeJGtTrtwuY6H2nlOBy6s4ltilqO6nkw/kuXfCcXCj5BOuVEaimyQnTnIbIvS70vc17aGDepPGu4bqXQZH2v4fJ3CZWAMOvijUO4A3iDf73/Bx9cHqsdpfzkNCP0WWASKP1BsJ6vtVAkXLeu1xBc218HEtv3FXIM0bO/GxPHwCc3ngk1RA43HrDTwGbnvuaRwk5yMGNs669Ci6nh2gkmS7ovG8ndlm8VHJsV6Ex7/3Cn44OYokpOlHH7S85EyCAEnO902FbUC8YpoXdUj48GXnyTifGGKbaSP+2w2PQGhypzwBkMZOs0wVItvyTwdMMC/DjnTYD7QmphR10SF8en/0QsGyj2lYzxE5mHwJPcvcL0ojDCgxGxRYyQLNhOjUagW2i5ZEaA4F0ZIWmwxMiq/9kHUXhXRBieeT2wROsKzGo/ItVNUGeKaEdIe6UZMhm9XIxo0NfryiKP2skos3XhlO8xXUamL3NcvIYeyXhWxJuhfRFsKjBtu2gs5vnzo3cpv4PHxLEUrO7dFyg+RzzTGz7EFYdqsDhFjDDjL6OAeUpk9wnUSy4/wXlHUWZBfpcX00inY00d5wNxS5q3iemc7STKZOzSGzPO5ATBwnzEn8T53KmLhhItpmct52nJfHHwWCKojedvHd4ZiJ+s=
    passphrase: Optional
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api_key:
      secure: DS/RdKFUfv0sOxS8QFer5du7vlGxUJCfFMKC3FtsNasCysfL/FaQLVvvyPiVH9k+t0X1ag7j9Die+xFe5h+hXAnnujK3iKU9vY5COWFA3ppBTKJeaJXz5okxiRFTF9jwBIrEbFOh29ouLfbQDvPwys6QJPN3mnmi26e6YAIqnBSkJvCfcjnN+WVSJkx9aPjomTqbDXflvEBMEeZiuB54Js7DLo9z/CKWhr1frKU2l61dWZYXROn1IOvci4qkULyxKQ6eCOUYqISTYtZ9/pqo6AczSLssFMqRjLwLdT6tqjhINdPTowV7/+eR7ITHfWqAttyE6ddecCb6RuE1eYxa0lIPTGf8TDiB527ieHaxy8mdac4oOYODTh4kdVqBOIJL4l7/OVYcEvpjbLhw7fFx7Oge6yk47FcxvGvZi3BwU7RPVbUB/5Q8kxOWioTprytiJfMFhNlBHvwcKhhTkufN6NTJnnzHU702VrWB/W8/IDaAPQebf44RpnHvoHsuBipgnn+BWwiCRQOJgeAIGeQe2wD0vQxzQ8AXzItQRI+/GOJqoSy99q9MyM+zV40CfY/wBmyVUKiKhHzfw5Vgcq7BpcT8s9OTxjjEP2Rio+ORCG9Awq6KkRmA1+Izu/Ta1+se068KR3Q7QUi6xOMl9/TneTm7qKkJikPbUCc1FAoHsLY=
    file_glob: true
    file:
      - ../*.orig.tar.*
      - ../*.debian.tar.*
      - ../*.dsc
    skip_cleanup: true
    on:
      tags: true

